- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Upgrade Ubuntu
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 1200

- name: Install common packages
  apt:
    name: "{{ system_common_packages }}"
    state: present
