- name: Install aptitude
  apt:
    name: aptitude
    state: installed

- name: Upgrade Ubuntu
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 1200

- name: Install common packages
  apt:
    name: "{{item}}"
    state: installed
  with_items: "{{ default_packages }}"

- name: Set timezone to Australia/Sydney
  timezone:
    name: "{{ ubuntu_timezone }}"

- name: Ensure ntpd is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Ensure boto aws python library is installed
  pip:
    name: "{{item}}"
  with_items: "{{ default_python_packages }}"

- include: setup_sar.yml
