- include_vars: "{{ ansible_os_family|lower }}.yml"

- include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Set timezone to {{ system_common_timezone }}
  timezone:
    name: "{{ system_common_timezone }}"

- name: Deploy time server config file
  template:
    src: chrony.conf.j2
    dest: "{{ system_common_ntp_config_path }}"

- name: Ensure time server is running
  service:
    name: "{{ system_common_ntp_service }}"
    state: started
    enabled: yes

- name: Ensure boto aws python library is installed
  pip:
    name: "{{ system_common_python_packages }}"

- include: setup_sar.yml

- name: add /etc/profile.d file to timestamp bash history
  template:
    src: etc/profile.d/bash_history_timestamp.sh
    dest: /etc/profile.d/bash_history_timestamp.sh
    mode: 0644
    owner: root
    group: root

# uid and gid should start from 1001 to maintain consistent across the board
- name: Create system group defined in system_groups dict
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ app_groups }}"
  when: app_groups is defined and app_groups

- name: Create system users defined in system_users dict
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid|default(omit) }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups|default(omit) }}"
    password: "{{ item.password|default(omit) }}"
    shell: "{{ item.shell|default(omit) }}"
    comment: "{{ item.comment|default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key|default(false) }}"
  with_items: "{{ app_users }}"
  when: app_users is defined and app_users
