- include_vars: "{{ ansible_os_family|lower }}.yml"

- include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Set timezone to {{ system_common_timezone }}
  timezone:
    name: "{{ system_common_timezone }}"

- name: Ensure ntpd is running
  service:
    name: "{{ system_common_ntp_service }}"
    state: started
    enabled: yes

- name: Ensure boto aws python library is installed
  pip:
    name: "{{item}}"
  with_items: "{{ system_common_python_packages }}"

- include: setup_sar.yml

- name: add /etc/profile.d file to timestamp bash history
  template:
    src: etc/profile.d/bash_history_timestamp.sh
    dest: /etc/profile.d/bash_history_timestamp.sh
    mode: 0644
    owner: root
    group: root
