- name: ensure postfix directory owned by postfix
  file:
    state: directory
    dest: /etc/postfix
    owner: postfix
    group: postfix

- name: install relay password file
  template:
    src: relay_password
    dest: /etc/postfix/relay_password
    mode: 0600
    owner: postfix
    group: postfix
  notify: update relay_password DB
  when: smtp_username is defined and smtp_password is defined

- name: install empty relay password file
  file:
    state: touch
    dest: /etc/postfix/relay_password
    mode: 0600
    owner: postfix
    group: postfix
  notify: update relay_password DB
  when: smtp_username is not defined or smtp_password is not defined

- name: install main.cf
  template:
    src: postfix.cf
    dest: /etc/postfix/main.cf
  notify: reload postfix

- name: ensure postfix is enabled and started
  service:
    name: postfix
    state: started
    enabled: yes
