- name: Add EPEL repo
  yum:
    name: epel-release
    state: present

- name: Upgrade OS
  yum:
    name: "*"
    state: latest

- name: Install common packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{ system_common_packages }}"
